INPUT:
  MIN_SIZE_TRAIN: [1278]
  MAX_SIZE_TRAIN: 2040
  MIN_SIZE_TEST: 1278
  MAX_SIZE_TEST: 2040
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  # WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  WEIGHT: "models/e2e_mask_rcnn_R_50/e2e_mask_rcnn_R_50_FPN_1x_no_last_layers.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    # ResNet50 contains of 5 stages, freeze first four stages
    FREEZE_CONV_BODY_AT: 4
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    NUM_CLASSES: 3
  RPN:
    USE_FPN: True
    ANCHOR_SIZES: (8, 16, 32, 64, 128)
    ANCHOR_STRIDE: (4, 4, 8, 16, 32)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    # Related to N images per GPU, here we have 3 images per GPU: 3×1000
    FPN_POST_NMS_TOP_N_TEST: 3000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    # Number of classes + 1 (background)
    NUM_CLASSES: 3
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPNFeatureExtractor"
    PREDICTOR: "MaskRCNNC4Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_pcards_synthetic_00_train",)
  TEST: ("coco_pcards_synthetic_00_test",)
  # TEST: ("coco_pcards_real_01_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (100000, 150000, 200000, 225000)
  MAX_ITER: 250000
  IMS_PER_BATCH: 24
OUTPUT_DIR: "models/pcards-03/"
TEST:
  IMS_PER_BATCH: 6
